#!/usr/bin/env sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
CONFIG="$XDG_CONFIG_HOME/inotifywatchdog/config"

if [ ! -e "$CONFIG" ]; then
	printf "%s: No such file\n" "$CONFIG" >&2
	exit 1
fi

inotifywait \
	--monitor \
	--event create \
	--event delete \
	--event modify \
	--event move \
	--format '%e %w%f' \
	--fromfile "$CONFIG_FILE" \
| while read -r event; do
	notify-send "Watchdog" "$event"
done
